################################################################################
##
## Copyright (C) 2005-2009 Red Hat, Inc. All rights reserved.
##
## This copyrighted material is made available to anyone wishing to use,
## modify, copy, or redistribute it subject to the terms and conditions
## of the GNU General Public License v.2.
##
################################################################################

include ../make/version.in
include ../make/defines.mk

all:

install:
	$(INSTALL_FILE) cluster_api.html ${docdir}/ricci-${VERSION}/
	$(INSTALL_FILE) logging_api.html ${docdir}/ricci-${VERSION}/
	$(INSTALL_FILE) modules_common.html ${docdir}/ricci-${VERSION}/
	$(INSTALL_FILE) modules.html ${docdir}/ricci-${VERSION}/
	$(INSTALL_FILE) reboot_api.html ${docdir}/ricci-${VERSION}/
	$(INSTALL_FILE) ricci_api.html ${docdir}/ricci-${VERSION}/
	$(INSTALL_FILE) rpm_api.html ${docdir}/ricci-${VERSION}/
	$(INSTALL_FILE) service_api.html ${docdir}/ricci-${VERSION}/
	$(INSTALL_FILE) storage_api.html ${docdir}/ricci-${VERSION}/
	$(INSTALL_FILE) storage-bds.html ${docdir}/ricci-${VERSION}/
	$(INSTALL_FILE) storage-bd_template.html ${docdir}/ricci-${VERSION}/
	$(INSTALL_FILE) storage-content.html ${docdir}/ricci-${VERSION}/
	$(INSTALL_FILE) storage-content_template.html ${docdir}/ricci-${VERSION}/
	$(INSTALL_FILE) storage-mappers.html ${docdir}/ricci-${VERSION}/
	$(INSTALL_FILE) storage-mapper_template.html ${docdir}/ricci-${VERSION}/
	$(INSTALL_FILE) variables.html ${docdir}/ricci-${VERSION}/
