/*
** Copyright (C) Red Hat, Inc. 2005-2008
**
** This program is free software; you can redistribute it and/or modify it
** under the terms of the GNU General Public License version 2 as
** published by the Free Software Foundation.
**
** This program is distributed in the hope that it will be useful, but
** WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
** General Public License for more details.
**
** You should have received a copy of the GNU General Public License
** along with this program; see the file COPYING. If not, write to the
** Free Software Foundation, Inc., 675 Mass Ave, Cambridge,
** MA 02139, USA.
*/

/*
 * Author: Stanko Kupcevic <kupcevic@redhat.com>
 */
/*
 * Note: this file originally auto-generated by mib2c using
 * : mib2c.column_defines.conf,v 5.1 2002/05/08 05:42:47 hardaker Exp $
 */

#ifndef __CONGA_MODCLUSTER_SNMP_NODESMIB_COLUMNS_H
#define __CONGA_MODCLUSTER_SNMP_NODESMIB_COLUMNS_H

/*
 * column number definitions for table rhcNodesTable
 */
#define COLUMN_RHCNODENAME						1
#define COLUMN_RHCNODESTATUSCODE				2
#define COLUMN_RHCNODESTATUSDESC				3
#define COLUMN_RHCNODERUNNINGSERVICESNUM		4
#define COLUMN_RHCNODERUNNINGSERVICESNAMES		5

#endif
